import { type FormEvent, useEffect, useState } from 'react';
import { getPreferences, type Preferences, updatePreferences } from '../services/profileService';

interface ProfilePageProps { user: { displayName: string; email: string }; onSignOut: () => void; }

export default function ProfilePage({ user, onSignOut }: ProfilePageProps) {
  const [preferences, setPreferences] = useState<Preferences>({ distanceUnit: 'km', weekStartsOn: 1, defaultCalendarView: 'week' });
  const [message, setMessage] = useState('');
  useEffect(() => { getPreferences().then(setPreferences).catch(() => setMessage('Could not load preferences.')); }, []);
  async function save(event: FormEvent) { event.preventDefault(); try { const saved = await updatePreferences(preferences); setPreferences(saved); setMessage('Preferences saved.'); } catch { setMessage('Could not save preferences.'); } }
  return <main><header className="page-header"><span className="page-kicker">Account</span><h1><span>Your</span> profile.</h1><p>Manage your Training Tracker account.</p></header><div className="profile-details"><div className="profile-avatar">{user.displayName.slice(0, 1).toUpperCase()}</div><dl><div><dt>Name</dt><dd>{user.displayName}</dd></div><div><dt>Email</dt><dd>{user.email}</dd></div></dl><button className="danger-button" type="button" onClick={onSignOut}>Sign out</button></div><section className="profile-preferences"><span className="section-kicker">Preferences</span><h2>Training settings</h2><form onSubmit={save}><label>Distance unit<select value={preferences.distanceUnit} onChange={(event) => setPreferences({ ...preferences, distanceUnit: event.target.value as Preferences['distanceUnit'] })}><option value="km">Kilometres (km)</option><option value="mi">Miles (mi)</option></select></label><label>Week starts on<select value={preferences.weekStartsOn} onChange={(event) => setPreferences({ ...preferences, weekStartsOn: Number(event.target.value) })}><option value={1}>Monday</option><option value={0}>Sunday</option></select></label><label>Default calendar view<select value={preferences.defaultCalendarView} onChange={(event) => setPreferences({ ...preferences, defaultCalendarView: event.target.value as Preferences['defaultCalendarView'] })}><option value="week">Week</option><option value="month">Month</option></select></label><button type="submit">Save preferences</button></form>{message && <p role="status">{message}</p>}</section></main>;
}
